language: objective-c
osx_image: xcode7.3
xcode_project: Demo/FMINestableTableViewDemo.xcodeproj
xcode_scheme: FMINestableTableViewDemo
#script: xctool -sdk iphonesimulator
script: xctool -project Demo/FMINestableTableViewDemo.xcodeproj -scheme FMINestableTableViewDemo build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO